name: rag-chatbot
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.7.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - krb5=1.21.3=hdf4eb48_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - liblzma=5.8.1=h2466b09_2
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.0=hf5d6505_0
  - libzlib=1.3.1=h2466b09_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h725018a_0
  - parso=0.8.5=pyhcf101f3_0
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py311hf893f09_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=h0159041_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - pywin32=311=py311hefeebc8_1
  - pyzmq=27.1.0=py311hb77b9c8_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=h2c6b04d_3
  - tornado=6.5.2=py311h3485c13_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - pip:
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - backoff==2.2.1
      - beautifulsoup4==4.14.2
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cryptography==46.0.3
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - emoji==2.15.0
      - faiss-cpu==1.11.0
      - filelock==3.20.0
      - filetype==1.2.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - greenlet==3.2.4
      - h11==0.16.0
      - html5lib==1.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - langchain==0.3.25
      - langchain-community==0.3.24
      - langchain-core==0.3.79
      - langchain-text-splitters==0.3.11
      - langdetect==1.0.9
      - langsmith==0.3.45
      - lxml==6.0.2
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - mpmath==1.3.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - narwhals==2.11.0
      - networkx==3.5
      - nltk==3.9.2
      - numpy==2.3.4
      - olefile==0.47
      - openai==1.79.0
      - orjson==3.11.4
      - packaging==24.2
      - pandas==2.3.3
      - pillow==11.3.0
      - propcache==0.4.1
      - protobuf==6.33.1
      - pyarrow==22.0.0
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pydeck==0.9.1
      - pypdf==6.3.0
      - pypdf2==3.0.1
      - python-dotenv==1.2.1
      - python-iso639==2025.11.11
      - python-magic==0.4.27
      - python-oxmsg==0.0.2
      - pytz==2025.2
      - pyyaml==6.0.3
      - rapidfuzz==3.14.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rpds-py==0.29.0
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - sentence-transformers==4.1.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - streamlit==1.45.1
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - torch==2.9.1
      - tqdm==4.67.1
      - transformers==4.57.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - unstructured==0.17.2
      - unstructured-client==0.42.4
      - urllib3==2.5.0
      - watchdog==6.0.0
      - webencodings==0.5.1
      - wrapt==2.0.1
      - yarl==1.22.0
      - zstandard==0.23.0
prefix: C:\Users\cmiyachi\AppData\Local\miniconda3\envs\rag-chatbot
